---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kweb-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: kubevirt
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: kubevirt-web-ui
    openshift.io/deployment-config.name: kubevirt-web-ui
  name: kubevirt-web-ui
  namespace: kubevirt
spec:
  replicas: 1
  selector:
    app: kubevirt-web-ui
    deployment: kubevirt-web-ui
    deploymentconfig: kubevirt-web-ui
  template:
    metadata:
      labels:
        app: kubevirt-web-ui
        deployment: kubevirt-web-ui
        deploymentconfig: kubevirt-web-ui
    spec:
      containers:
        - image: quay.io/kubevirt/kubevirt-web-ui:latest
          imagePullPolicy: IfNotPresent
          name: kubevirt-web-ui
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubevirt-web-ui
  name: kubevirt-web-ui
  namespace: kubevirt
spec:
  ports:
    - name: https
      nodePort: 30000
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    deploymentconfig: kubevirt-web-ui
  sessionAffinity: None
  type: NodePort
