{
 "title": "KubeVirt",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "VMs CPU time in sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kubevirt_vm_vcpu_seconds[5m])) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "API client request - 2xx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"2..\",job=\"kubevirt-prometheus-metrics\"}[5m]))",
     "legendFormat": "Code 2xx"
    }
   ]
  },
  {
   "title": "VMs IOPs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vm_storage_iops_total[5m])) by (domain,type)",
     "legendFormat": "{{domain}} - {{type}}"
    }
   ]
  },
  {
   "title": "API client request - 4xx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"4..\",job=\"kubevirt-prometheus-metrics\"}[5m]))",
     "legendFormat": "Code 5XX"
    }
   ]
  },
  {
   "title": "VMs resident memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kubevirt_vm_memory_resident_bytes) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "API client request - 5xx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=~\"5..\",job=\"kubevirt-prometheus-metrics\"}[5m])) or vector(0)",
     "legendFormat": "Code 5XX"
    }
   ]
  },
  {
   "title": "VMs Network Traffic in bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubevirt_vm_network_traffic_bytes_total[5m])) by (domain,type)",
     "legendFormat": "{{domain}} - {{type}}"
    }
   ]
  },
  {
   "title": "API client request - errors",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=\"<error>\",job=\"kubevirt-prometheus-metrics\"}[5m])) or vector(0)",
     "legendFormat": "Code <error>"
    }
   ]
  }
 ]
}