#!/bin/bash
#
# This file is part of the KubeVirt project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2019 Red Hat, Inc.
#

set +e

function install_mdsh() {
	# Download and install mdsh
	mkdir -p ${HOME}/bin
	wget https://raw.githubusercontent.com/bashup/mdsh/master/bin/mdsh -O ${HOME}/bin/mdsh
	chmod 755 ${HOME}/bin/mdsh
}

function validations() {
	# Common duties to perform before the script execution

	BASE_PATH="$(pwd)"
	BUILD_PATH="${BASE_PATH}/build"
	mkdir -p "${BUILD_PATH}"

	# Look for mdsh executable
	type mdsh || install_mdsh

    if [[ ! -e ${BASE_PATH}/${1} ]]; then
		echo "Error: File or Folder doesn't exists"
		exit -1
    fi
        
}

function create_binaries() {
    # This function will generate the necessary resultant scripts
    # from MD files
	echo "Generating script files..."
    md_path="$1"

    if [[ -d ${BASE_PATH}/${md_path} ]]; then
		while IFS=  read -r -d $'\0'; do
			mdsh --out "${BUILD_PATH}/$(basename ${REPLY%.*}).sh" -c "${REPLY}"
		done < <(find "${BASE_PATH}/${md_path}" -name "*.md" -print0)
	elif [[ -f "${BASE_PATH}/${md_path}" ]]; then
        mdsh --out "${BUILD_PATH}/$(basename ${md_path%.*}).sh" -c "${md_path}"
	else
		echo "Error: File or Folder doesn't exists"
		exit -1
    fi

	# Concatenate sh files into the all-in-one test
	find "${BUILD_PATH}" -name "*.sh" -print0 | sort -z | xargs -0 cat > "/tmp/all-labs.sh"
	rm -f ${BUILD_PATH}/*
	mv "/tmp/all-labs.sh" "${BUILD_PATH}/all-labs.sh"

    echo "Done!"

}

# $1 is the relative path where the MD files are located

validations "$1"
create_binaries "$1"
