apiVersion: v1
kind: Template
metadata:
  name: ara
  annotations:
    description: "ara"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ara
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ara
  spec:
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: ara:latest
    source:
      git:
        uri: "https://github.com/jcpowermac/openshift-presentation"
        ref: "master"
      contextDir: lab/ara 
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ara
    name: ara
  spec:
    replicas: 1
    selector:
      app: ara
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ara
      spec:
        containers:
        - env:
          - name: ARA_HOST
            value: 0.0.0.0
          - name: ARA_PORT
            value: "8080"
          image: ''
          name: ara
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - ara
        from:
          kind: ImageStreamTag
          name: 'ara:latest'
      type: ImageChange

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ara
    name: ara
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ara
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ara
    name: ara
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ara
